# -*- coding: utf-8 -*-
"""BlobDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f33uwjxEAA0v8lUGNaoAhGLvpy-V5Cdn
"""

#import the libraries
from google.colab.patches import cv2_imshow
import cv2
import numpy as np
#Read the Image and Display the image.
img=cv2.imread("blood.jpg")
cv2_imshow(img);
print("Processed Image")
detector = cv2.SimpleBlobDetector_create()
keypoints = detector.detect(img)
im_with_keypoints = cv2.drawKeypoints(img, keypoints, np.array([]), (0,0,255), cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
Processed_img=im_with_keypoints;
#Displaying Processed image
cv2_imshow(Processed_img)
cv2.waitKey(0)